service: next-auth-example

provider:
  name: aws
  # profile:
  region: 'ap-northeast-2'
  stage: 'dev'
  runtime: nodejs16.x
  stackName: ${self:provider.stage}-${self:service}
  apiName: ${self:provider.stage}-${self:service}
  timeout: 25
  memorySize: 2048
  versionFunctions: false
	apiGateway:
    binaryMediaTypes:
      - '*/*'

  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: production
    # .env 파일의 내용을 모두 입력해줍니다.

functions:
  app:
    handler: index.handle
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any

package:
  individually: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: next-auth.nalbam.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: arn:aws:acm:us-east-1:968005369378:certificate/b01e68e2-aaa9-410e-97fa-8f1ed4c18c7d
    securityPolicy: tls_1_2
