# org: nalbam
app: next-auth-example
service: next-auth-example

provider:
  name: aws
  region: "ap-northeast-2"
  stage: "dev"
  # stackName: ${self:service}-${self:provider.stage}
  # apiName: ${self:service}-${self:provider.stage}
  timeout: 60
  memorySize: 3072
  apiGateway:
    binaryMediaTypes:
      - "*/*"
    apiKeys:
      - name: next-auth-example-key
        description: API key for next-auth-example
    usagePlan:
      quota:
        limit: 5000
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  # tracing:
  #   apiGateway: true
  #   lambda: true
  environment:
    NODE_ENV: production
  architecture: x86_64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - ecr:BatchCheckLayerAvailability
          Resource: "*"

functions:
  app:
    image: ${self:custom.image}
    events:
      - http:
          cors: true
          path: "/"
          method: any
          timeout: 30
      - http:
          cors: true
          path: "{proxy+}"
          method: any
          timeout: 30
    warmup:
      enabled: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
  # - serverless-domain-manager

custom:
  # Docker 이미지 URI 정의
  image: 968005369378.dkr.ecr.ap-northeast-2.amazonaws.com/nalbam/next-auth-example:latest

  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)

  # customDomain:
  #   domainName: next-auth.nalbam.com
  #   basePath: ""
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true
  #   certificateName: arn:aws:acm:us-east-1:968005369378:certificate/b01e68e2-aaa9-410e-97fa-8f1ed4c18c7d
  #   securityPolicy: tls_1_2
