# org: nalbam
app: next-auth-example
service: next-auth-example

provider:
  name: aws
  region: 'ap-northeast-2'
  stage: 'dev'
  # stackName: ${self:service}-${self:provider.stage}
  # apiName: ${self:service}-${self:provider.stage}
  timeout: 29
  memorySize: 2048
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  # tracing:
  #   apiGateway: true
  #   lambda: true
  environment:
    NODE_ENV: dev
  architecture: x86_64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - ecr:BatchCheckLayerAvailability
          Resource: "*"

functions:
  app:
    image: ${self:custom.image}
    # events:
    #   - httpApi: '*'
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
    # warmup:
    #   enabled: true

plugins:
  - serverless-dotenv-plugin
  # - serverless-domain-manager
  # - serverless-plugin-warmup

custom:
  # Docker 이미지 URI 정의
  image: 968005369378.dkr.ecr.ap-northeast-2.amazonaws.com/nalbam/next-auth-example:latest
#   # customDomain:
#   #   domainName: next-auth.nalbam.com
#   #   basePath: ''
#   #   stage: ${self:provider.stage}
#   #   createRoute53Record: true
#   #   certificateName: arn:aws:acm:us-east-1:968005369378:certificate/b01e68e2-aaa9-410e-97fa-8f1ed4c18c7d
#   #   securityPolicy: tls_1_2

#   warmup:
#     enabled: true
#     events:
#       - schedule: rate(5 minutes)
