service: next-auth-example

provider:
  name: aws
  # profile:
  region: 'ap-northeast-2'
  stage: 'dev'
  runtime: nodejs16.x
  stackName: ${self:provider.stage}-${self:service}
  apiName: ${self:provider.stage}-${self:service}
  timeout: 25
  memorySize: 2048
  versionFunctions: false
	apiGateway:
    binaryMediaTypes:
      - '*/*'

  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: production
    # .env 파일의 내용을 모두 입력해줍니다.

functions:
  app:
    handler: index.handle
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any

package:
  individually: true

# plugins:
#   - serverless-domain-manager

# custom:
#   customDomain:
#     domainName: # 사용할 도메인
#     basePath: ''
#     stage: ${self:provider.stage}
#     createRoute53Record: true
#     certificateName: # Certification Manager에 등록된 인증서 이름
#     securityPolicy: tls_1_2
